# config.py

EMBED_MODEL = "RPRTHPB-text-embedding-3-small"
CHAT_MODEL  = "RPRTHPB-gpt-5-mini"

CHUNK_SIZE     = 1024
OVERLAP_RATIO  = 0.2
TOP_K_QUERY    = 30

OVERLAP_CHARS = int(CHUNK_SIZE * OVERLAP_RATIO)
STEP = CHUNK_SIZE - OVERLAP_CHARS
